name = "Chemicals"
uuid = "4abf17f3-5646-4579-aa1e-e1e9ebf23bb1"
authors = ["longemen3000 <longemen3000@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
